[package]
name = "automarkddang"
version = "0.1.0"
authors = ["Changseok Han <freestrings@gmail.com>"]

[dependencies]
clap = "2"
rtag = "0.3.1"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
time = "*"