[package]
name = "automark"
version = "0.2.0"
authors = ["Changseok Han <freestrings@gmail.com>"]

[dependencies]
clap = "2"
rtag = "0.3.2"
log = "0.3"
env_logger = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
time = "*"